=== naryeen/FID/collect-master/collect-core/src/main/resources/idml3-ui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  elementFormDefault="qualified" version="1.0"
  xmlns="http://www.openforis.org/collect/3.0/ui" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:idml="http://www.openforis.org/idml/3.0" 
  targetNamespace="http://www.openforis.org/collect/3.0/ui"
  >
  <xs:annotation>
    <xs:documentation xml:lang="en">
      Inventory Data Modeling Language 3.0 - Collect UI Options
      S. Ricci
    </xs:documentation>
  </xs:annotation>

  <xs:import namespace="http://www.openforis.org/idml/3.0" 
    schemaLocation="https://raw.github.com/openforis/collect/master/collect-core/src/main/resources/idml3.xsd"/>
  
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
  <!-- Types used throughout this schema -->
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

  <xs:complexType name="tabSet">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Set of tabs
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="tab" type="tab" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            TO-DO
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string">
      <xs:annotation>
        <xs:documentation xml:lang="en">
          Name of the tab set.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="tab">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        TO-DO
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="tabSet">
        <xs:sequence>
          <xs:element name="label" minOccurs="1"  maxOccurs="unbounded"
            type="idml:unformattedText">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                TO-DO
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="tab" type="tab" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                TO-DO
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="tabSet" type="tabSet">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Group of tabs element. 
        Each root entity must be associated to a tabSet, using ui:tabSet annotation
      </xs:documentation>
    </xs:annotation>
  </xs:element>

</xs:schema>

=== naryeen/FID/collect-master/collect-core/src/test/resources/test-uioptions.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabSet 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.openforis.org/collect/3.0/ui"
      xsi:schemaLocation="http://www.openforis.org/collect/3.0/ui ../../main/resources/idml3-ui.xsd"
      name="cluster">
  <tab name="cluster">
    <label xml:lang="en">Cluster</label>
  </tab>
  <tab name="plot">
    <label xml:lang="en">Plot</label>
    <tab name="plot_det">
      <label xml:lang="en">Details (2)</label>
    </tab>
    <tab name="shrubs_regen">
      <label xml:lang="en">Shrubs &amp; Regeneration (3)</label>
    </tab>
    <tab name="tree">
      <label xml:lang="en">Trees (4)</label>
    </tab>
    <tab name="dead_wood">
      <label xml:lang="en">Dead Wood (5a)</label>
    </tab>
    <tab name="stump">
      <label xml:lang="en">Stumps (5b)</label>
    </tab>
    <tab name="bamboo">
      <label xml:lang="en">Bamboo (6)</label>
    </tab>
  </tab>
  <tab name="informant">
    <label xml:lang="en">Informant Interviews</label>
  </tab>
  <tab name="household">
    <label xml:lang="en">Household Surveys</label>
    <tab name="hs_general">
      <label xml:lang="en">General (A/B/C)</label>
    </tab>
    <tab name="hs_assets">
      <label xml:lang="en">Assets (D)</label>
    </tab>
    <tab name="hs_foodsecurity">
      <label xml:lang="en">Food Security (E)</label>
    </tab>
    <tab name="hs_income_opinions">
      <label xml:lang="en">Income &amp; Opinions (F/G)</label>
    </tab>
    <tab name="hs_forest_products">
      <label xml:lang="en">Forest Products &amp; Services (H)</label>
    </tab>
    <tab name="hs_org_comments">
      <label xml:lang="en">Organizations &amp; Comments (I/J)</label>
    </tab>
    <tab name="hs_forest_governance">
      <label xml:lang="en">Forest Governance (K)</label>
    </tab>
    <tab name="hs_comments">
      <label xml:lang="en">Comments</label>
    </tab>
  </tab>
</tabSet>
